apiVersion: apps/v1
kind: Deployment
metadata:
  name: Demo-Devops
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: bharath143ongole/demo-devops:1.1
        ports:
        - containerPort: 8080
